name: Auditing

on:
  push:
    paths:
      - 'Formula/*.rb'

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Audit
        uses: jonchang/audit-action@master
