name: Build and upload bottles

on: pull_request

jobs:
  build-linux:
    runs-on: ubuntu-latest
    container: linuxbrew/brew
    steps:
      - name: Checkout tap
        uses: actions/checkout@v1
      - name: Setup tap
        run: |
          mkdir -p "$(brew --prefix)/Homebrew/Library/Taps/dawidd6"
          ln -s "$PWD" "$(brew --prefix)/Homebrew/Library/Taps/$GITHUB_REPOSITORY"
      - name: Build bottles
        env:
          # Seems like Github is mounting some volumes in home and workdir place.
          # Setting these help avoiding "Invalid cross-device link" errors.
          HOMEBREW_CACHE: /home/linuxbrew/.cache
          HOMEBREW_TEMP: /home/linuxbrew/.tmp
          HOMEBREW_BINTRAY_USER: dawidd6
          HOMEBREW_BINTRAY_REPO: bottles-tap
        run: |
          mkdir /bottles
          cd /bottles
          GITHUB_ACTIONS=true brew test-bot --root-url=https://dl.bintray.com/$HOMEBREW_BINTRAY_USER/$HOMEBREW_BINTRAY_REPO
          ls *.bottle.* && mkdir $GITHUB_WORKSPACE/bottles && mv *.bottle.* $GITHUB_WORKSPACE/bottles
      - name: Cache bottles
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: bottles-linux
          path: bottles
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout tap
        uses: actions/checkout@v1
      - name: Setup tap
        run: |
          mkdir -p "$(brew --prefix)/Homebrew/Library/Taps/dawidd6"
          ln -s "$PWD" "$(brew --prefix)/Homebrew/Library/Taps/$GITHUB_REPOSITORY"
      - name: Tap dawidd6/test-bot
        run: |
          brew tap dawidd6/test-bot
          cd $(brew --repository dawidd6/test-bot)/../..
          mv dawidd6/homebrew-test-bot homebrew
      - name: Build bottles
        env:
          HOMEBREW_BINTRAY_USER: dawidd6
          HOMEBREW_BINTRAY_REPO: bottles-tap
        run: |
          mkdir bottles
          cd bottles
          brew test-bot --root-url=https://dl.bintray.com/$HOMEBREW_BINTRAY_USER/$HOMEBREW_BINTRAY_REPO
      - name: Cache bottles
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: bottles-macos
          path: bottles
  upload:
    runs-on: macos-latest
    needs:
      - build-linux
      - build-macos
    steps:
      - name: Get bottles-linux
        uses: actions/download-artifact@v1
        with:
          name: bottles-linux
          path: ./
      - name: Get bottles-macos
        uses: actions/download-artifact@v1
        with:
          name: bottles-macos
          path: ./
      - name: Upload bottles
        env:
          HOMEBREW_BOTTLE_DOMAIN: https://dl.bintray.com/dawidd6
          HOMEBREW_BINTRAY_USER: dawidd6
          HOMEBREW_BINTRAY_REPO: bottles-tap
          HOMEBREW_BINTRAY_KEY: ${{secrets.HOMEBREW_BINTRAY_KEY}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          # Exit immediately if any command fails.
          set -e
          # Should exit if no bottles.
          ls *.bottle.* || exit 0
          # Create packages on bintray if they don't exist.
          for package in $(ls -1 *.bottle.* | awk -F '--' '{print $1}' | uniq); do
            curl \
              --user $HOMEBREW_BINTRAY_USER:$HOMEBREW_BINTRAY_KEY \
              --header "Content-Type: application/json" \
              --data " \
                {\"name\": \"$package\", \
                \"vcs_url\": \"$GITHUB_REPOSITORY\", \
                \"licenses\": [\"MIT\"], \
                \"public_download_numbers\": true, \
                \"public_stats\": true \
                }" \
              https://api.bintray.com/packages/$HOMEBREW_BINTRAY_USER/$HOMEBREW_BINTRAY_REPO || true
          done
          # Upload bottles from current directory.
          brew update
          brew test-bot --bintray-org=$HOMEBREW_BINTRAY_USER --ci-upload
          # Push changes.
          cd $(brew --repository $GITHUB_REPOSITORY)
          git checkout -B \
            pr-${{github.event.pull_request.number}}
          git push --force \
            https://$HOMEBREW_BINTRAY_USER:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git \
            pr-${{github.event.pull_request.number}}
