name: Build and upload bottles

on: pull_request

jobs:
  build-linux:
    runs-on: ubuntu-latest
    container: linuxbrew/brew
    steps:
      - name: Checkout tap
        uses: actions/checkout@v1
      - name: Setup tap
        run: |
          mkdir -p "$(brew --prefix)/Homebrew/Library/Taps/dawidd6"
          ln -s "$PWD" "$(brew --prefix)/Homebrew/Library/Taps/$GITHUB_REPOSITORY"
      - name: Build bottles
        env:
          # Seems like Github is mounting some volumes in home and workdir place.
          # Setting these help avoiding "Invalid cross-device link" errors.
          HOMEBREW_CACHE: /home/linuxbrew/.cache
          HOMEBREW_TEMP: /home/linuxbrew/.tmp
        run: |
          # workaround, github mounts a volume in workspace dir and brew complains about it
          cd $(brew --prefix)
          # workaround, GITHUB_ACTIONS is not set in containers, only in VMs
          GITHUB_ACTIONS=true brew test-bot --root-url=https://dl.bintray.com/dawidd6/bottles-tap
          # workaround, github mounts a volume in workspace dir and brew complains about it
          ls *.bottle.* && cp $(brew --prefix)/*.bottle.* $GITHUB_WORKSPACE
      - name: Cache bottles
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: bottles-linux
          path: ./
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout tap
        uses: actions/checkout@v1
      - name: Setup tap
        run: |
          mkdir -p "$(brew --prefix)/Homebrew/Library/Taps/dawidd6"
          ln -s "$PWD" "$(brew --prefix)/Homebrew/Library/Taps/$GITHUB_REPOSITORY"
      - name: Build bottles
        run: |
          brew test-bot --root-url=https://dl.bintray.com/dawidd6/bottles-tap
      - name: Cache bottles
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: bottles-macos
          path: ./
  upload:
    runs-on: macos-latest
    needs:
      - build-linux
      - build-macos
    steps:
      - name: Get bottles-linux
        uses: actions/download-artifact@v1
        with:
          name: bottles-linux
          path: ./
      - name: Get bottles-macos
        uses: actions/download-artifact@v1
        with:
          name: bottles-macos
          path: ./
      - name: Upload bottles
        env:
          HOMEBREW_BOTTLE_DOMAIN: https://dl.bintray.com/dawidd6
          HOMEBREW_BINTRAY_USER: dawidd6
          HOMEBREW_BINTRAY_REPO: bottles-tap
          HOMEBREW_BINTRAY_KEY: ${{secrets.HOMEBREW_BINTRAY_KEY}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          # Exit immediately if any command fails.
          set -e
          # Should exit if no bottles.
          ls *.bottle.* || exit 0
          # Get packages names.
          PACKAGES=($(ls -1 *bottle.json | awk -F '--' '{print $1}' | uniq))
          # Create packages on bintray if they don't exist.
          for package in ${PACKAGES[@]}; do
            curl \
              --user $HOMEBREW_BINTRAY_USER:$HOMEBREW_BINTRAY_KEY \
              --header "Content-Type: application/json" \
              --data " \
                {\"name\": \"$package\", \
                \"vcs_url\": \"$GITHUB_REPOSITORY\", \
                \"licenses\": [\"MIT\"], \
                \"public_download_numbers\": true, \
                \"public_stats\": true \
                }" \
              https://api.bintray.com/packages/$HOMEBREW_BINTRAY_USER/$HOMEBREW_BINTRAY_REPO || true
          done
          # Upload bottles from current directory.
          brew update
          brew test-bot --bintray-org=$HOMEBREW_BINTRAY_USER --ci-upload
          # Push changes.
          cd $(brew --repository ${{github.repository}})
          git checkout -B \
            pr-${{github.event.pull_request.number}}
          git push --force \
            https://$HOMEBREW_BINTRAY_USER:$GITHUB_TOKEN@github.com/${{github.repository}}.git \
            pr-${{github.event.pull_request.number}}
