name: Build and upload bottles

on: pull_request

jobs:
  build-linux:
    runs-on: ubuntu-latest
    container: linuxbrew/brew
    steps:
      - name: Setup git
        run: |
          git config --global user.email "testbot@homebrew.sh"
          git config --global user.name "BrewTestBot"
      - name: Build bottles
        env:
          # Seems like Github is mounting some volumes in home and workdir place.
          # Setting these help avoiding "Invalid cross-device link" errors.
          HOMEBREW_CACHE: /home/linuxbrew/.cache
          HOMEBREW_TEMP: /home/linuxbrew/.tmp
          HOMEBREW_BINTRAY_USER: dawidd6
          HOMEBREW_BINTRAY_REPO: bottles-tap
        run: |
          # workaround, github mounts a volume in workspace dir and brew complains about it
          cd $(brew --prefix)
          # workaround, GITHUB_ACTIONS is not set in containers, only in VMs
          brew test-bot --verbose --root-url=https://dl.bintray.com/$HOMEBREW_BINTRAY_USER/$HOMEBREW_BINTRAY_REPO
          # workaround, github mounts a volume in workspace dir and brew complains about it
          if ls *.bottle.* && cp $(brew --prefix)/*.bottle.* $GITHUB_WORKSPACE || true
      - name: Cache bottles
        uses: actions/upload-artifact@v1
        with:
          name: bottles
          path: ./
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Setup git
        run: |
          git config --global user.email "testbot@homebrew.sh"
          git config --global user.name "BrewTestBot"
      - name: Checkout PR
        run: |
          brew tap ${{github.repository}}
          cd $(brew --repository ${{github.repository}})
          git checkout -b pr-test
          git fetch origin master:master ${{github.event.pull_request.head.ref}}:pr
          git checkout pr
      - name: Build bottles
        env:
          HOMEBREW_BINTRAY_USER: dawidd6
          HOMEBREW_BINTRAY_REPO: bottles-tap
        run: |
          brew test-bot --root-url=https://dl.bintray.com/$HOMEBREW_BINTRAY_USER/$HOMEBREW_BINTRAY_REPO
      - name: Cache bottles
        uses: actions/upload-artifact@v1
        with:
          name: bottles
          path: ./
  upload:
    runs-on: macos-latest
    needs:
      - build-linux
      - build-macos
    steps:
      - name: Get bottles
        uses: actions/download-artifact@v1
        with:
          name: bottles
      - name: Upload bottles
        env:
          HOMEBREW_BINTRAY_USER: dawidd6
          HOMEBREW_BINTRAY_REPO: bottles-tap
          HOMEBREW_BINTRAY_KEY: ${{secrets.HOMEBREW_BINTRAY_KEY}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          JFROG_CLI_OFFER_CONFIG: false
        run: |
          # Exit immediately if any command fails.
          set -e
          # Should exit if no bottles.
          ls *bottle.json
          # Run `brew update` so we hopefully avoid:
          # "Formula loading disabled by HOMEBREW_DISABLE_LOAD_FORMULA!".
          brew update
          # Install this utility so we can create packages on bintray.
          brew install jfrog-cli-go
          # Get package name.
          PACKAGE="$(ls *bottle.json | awk -F '--' '{print $1}')"
          # Create package on bintray if it doesn't exist.
          jfrog bt package-show \
            --user=$HOMEBREW_BINTRAY_USER \
            --key=$HOMEBREW_BINTRAY_KEY \
            $HOMEBREW_BINTRAY_USER/$HOMEBREW_BINTRAY_REPO/$PACKAGE || \
          jfrog bt package-create \
            --user=$HOMEBREW_BINTRAY_USER \
            --key=$HOMEBREW_BINTRAY_KEY \
            --vcs-url=${{github.repository}} \
            --licenses=MIT \
            $HOMEBREW_BINTRAY_USER/$HOMEBREW_BINTRAY_REPO/$PACKAGE
          # Upload bottles from current directory.
          brew test-bot --bintray-org=$HOMEBREW_BINTRAY_USER --ci-upload
          # Push changes.
          cd $(brew --repository ${{github.repository}})
          git checkout -B \
            pr-${{github.event.pull_request.number}}
          git push --force \
            https://$HOMEBREW_BINTRAY_USER:$GITHUB_TOKEN@github.com/${{github.repository}}.git \
            pr-${{github.event.pull_request.number}}
