name: Checking

on:
  push:
    branches: master
  schedule:
    # At 06:00 on Friday
    - cron: '0 6 * * 5'

jobs:
  check:
    runs-on: ubuntu-latest
    container:
      image: homebrew/brew
      env:
        HOMEBREW_NO_AUTO_UPDATE: 1
        HOMEBREW_NO_CLEANUP: 1
        FILENAME: livecheck.txt
    steps:
      - name: Tap
        run: |
          brew tap homebrew/livecheck
          brew tap ${{github.repository}}
      - name: Check
        id: check
        run: |
          brew livecheck -n -q --tap=${{github.repository}} > ${{env.FILENAME}}
          wc -l ${{env.FILENAME}} | grep -vq '^0 ' && echo "::set-output name=check::true"
      - name: Send
        if: steps.check.outputs.check != ''
        uses: dawidd6/action-send-mail@v1.1.0
        with:
          server_address: ${{secrets.MAIL_SERVER}}
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Outdated formulae in ${{github.repository}}
          body: ${{env.FILENAME}}
          to: ${{secrets.MAIL_TO}}
          from: github-actions
