name: Clean branches

on:
  push:
    branches:
      - master

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: Clean branches
        uses: ./.github/actions/cleaning
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
