name: Clean branches

on:
  push:
    branches:
      - master

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - name: Install octokit
        run: gem install octokit
      - name: Clean branches
        run: ./.github/workflows/cleaning.rb
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
