name: Test

on:
  push:
    branches: master

jobs:
  test-linux:
    runs-on: ubuntu-latest
    container: linuxbrew/brew
    steps:
      - run: |
          echo $GITHUB_ACTIONS
  test-macos:
    runs-on: macos-latest
    steps:
      - run: |
          echo $GITHUB_ACTIONS
